In [83]:
# Importing Dependencies
import pandas as pd
import numpy as np

# Data Preproccessing

In [84]:
# Import the 2019 Data (Training Data)
df_2019 = pd.read_csv('Resources/2019loans.csv')
df_2019.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

In [85]:
# Converting Categorical Data into numeric
df_2019_dummies = pd.get_dummies(df_2019)
df_2019_dummies.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,1,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,1,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,1,1,0,1,1,0,1,0,1,0

In [98]:
# Extracting the target Features [loan_status_low_risk , loan_status_high_risk]

target_features = df_2019['loan_status'].unique() # finding the unique categorical value to be converted into columns

X_train = df_2019_dummies.drop(['loan_status_low_risk' , 'loan_status_high_risk' , 'Unnamed: 0'] , axis=1)
y_train = df_2019_dummies[ 'loan_status_high_risk']

In [87]:
# Reading in 2020 data
df_2020 = pd.read_csv('Resources/2020Q1loans.csv')
df_2020.head()

# Dropping the redundant Unnanmed: 0 column
df_2020.drop('Unnamed: 0' , axis=1 , inplace= True)

In [88]:
# Converting cat data into numeric
df_2020_dummies = pd.get_dummies(df_2020)
df_2020_dummies.head()

,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,loan_status_high_risk,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,67991,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,0.0,...,0,1,1,0,1,1,0,1,0,1
1,25429,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,0.0,...,0,1,1,0,1,1,0,1,0,1
2,38496,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,0.0,...,0,1,1,0,1,1,0,1,0,1
3,19667,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,0.0,...,0,1,1,0,1,1,0,1,0,1
4,37505,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,0.0,...,0,1,1,0,1,1,0,1,0,1

In [89]:
# Finding the column that is missing in our test data set

cols_2019 = list(df_2019_dummies.columns) # columns in 2019 dummy dataset

cols_2020 = list(df_2020_dummies.columns) # columns in 2020 dummy dataset

# Find the missing feature
missing_features = []

for feature in cols_2019:

    if feature not in cols_2020:
        missing_features.append(feature)
        
    
print(missing_features)

['Unnamed: 0', 'debt_settlement_flag_Y']

The missing data can be imputed from debt_settlement_flag_N due to the binary origin of the column
... That is, if debt_settlement_N is True then deb_settlement_Y is False ,
Knowing that we can create an artificial column of data so that our training and test sets have the same shape

In [90]:
# Filling in the missing data in the debt_settlement_flag_Y column
new_col =  []
for value in df_2020_dummies['debt_settlement_flag_N']:

    if value == 1:
        new_col.append(0)
    else:
        new_col.append(1)

df_2020_dummies['debt_settlement_flag_Y'] = new_col

In [102]:
X_test = df_2020_dummies.drop(['loan_status_low_risk' , 'loan_status_high_risk'] , axis=1)
y_test = df_2019_dummies[ 'loan_status_high_risk']
print(len(X_test))
print(len(y_test))

4702
12180

# Modeling
Random Forest:
* implicitly performs feature selection , making it great when there are a large number of features , we have 93 here
* bins variables making it resistant to outliers
* can handle linear and non linear relationships
* provide high accuracy and balance the bias-variance trade-off well
*  https://medium.datadriveninvestor.com/random-forest-pros-and-cons-c1c42fb64f04

Logistic Regression:
* weak against non-linear relationships but effective against linear ones
* sometimes simple is better and outputs are interpretable as probabilities
* https://www.geeksforgeeks.org/advantages-and-disadvantages-of-logistic-regression/

## Predictions
Since most data in the real world is not linear I have a hunch that vanilla logistic regression will underperform.

In [100]:
# fitting the training data to our logistic and random forest classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

LR = LogisticRegression().fit(X_train , y_train)
print(f'Training Score: {LR.score(X_train , y_train)}')
print(f'Test Score: {LR.score(X_test , y_test)}')

Training Score: 0.6575533661740558

C:\Users\daypa\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

ValueError: Found input variables with inconsistent numbers of samples: [12180, 4702]